### ISSUE TITLE
Tests fail when using Java 11

### ISSUE THREAD

**Issue by ekrich** [ekrich/sconfig#4]
I looks to be related to properties, `java.version`.

**Comment by SethTisue** [comment]
seen in Scala community build at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk11-integrate-community-build/307/consoleFull

```
[sconfig] [error] Test ApiExamples.readSomeConfig failed: org.ekrich.config.ConfigException$WrongType: test01.conf @ file:/home/jenkins/workspace/scala-2.12.x-jdk11-integrate-community-build/target-0.9.16/project-builds/sconfig-385e2a160a3205ae4e304a8fb591fae994ca98f6/sconfig/target/scala-2.12.9-bin-7f1658e/test-classes/test01.conf: 92: Cannot concatenate object or list with a non-object-or-list, Quoted("Your Java version is ") and SimpleConfigObject({"date":"2018-10-16"}) are not compatible, took 0.064 sec
[sconfig] [error]     at org.ekrich.config.impl.ConfigConcatenation$.join(ConfigConcatenation.scala:70)
[sconfig] [error]     at org.ekrich.config.impl.ConfigConcatenation$.$anonfun$consolidate$2(ConfigConcatenation.scala:99)
```

**Comment by SethTisue** [comment]
once this is fixed, #16 will prevent backsliding

**Comment by SethTisue** [comment]
once this is fixed, #16 could be reopened and merged to prevent backsliding

**Comment by ekrich** [comment]
JDK 11 added a java.version.date property. Could it be parsed, merged as follows?
```
{
   "java":{
      "version":[
         "11.0.1",
         {
            "date":"2018-10-16"
         }
      ]
   }
}
```
This means that when there are mixed types under a node they should be modeled as an `Array` of `AnyRef` to use Scala terms.

**Comment by SethTisue** [comment]
no clue, I'm just the community build guy in this :-)

**Comment by ekrich** [comment]
No worries, just wanted to let you know that I looked into this so I definitely am not ignoring you. I also want to get this working on `2.13.0` as well.

**Comment by ekrich** [comment]
Resolved via https://github.com/ekrich/sconfig/pull/42
