### ISSUE TITLE
Consider providing a compatibility layer for com.typesafehub

### ISSUE THREAD

**Issue by jokade** [ekrich/sconfig#67]
Although I appreciate the issues with hijacking another namespace, it would be really helpful if sconfig came with a 'compatibility' layer so that it can be used as a drop-in for `com.typesafehub.Config`.

**Comment by ekrich** [comment]
This is a good idea.

**Comment by ekrich** [comment]
Closed via #191 - I think the addition of `scalafix` to migrate the code is a good compromise.
